version: '3'

services:
    db_dev:
        image: mysql:5.7
        ports:
            - "3307:3306"
        volumes:
            - ${BASE_PATH}.data_dev/db:/var/lib/mysql:rw
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "team"
            MYSQL_PASSWORD: "team"
            MYSQL_DATABASE: "team_db"
        networks:
            - code-network

    db_test:
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - ${BASE_PATH}.data_test/db:/var/lib/mysql:rw
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "team"
            MYSQL_PASSWORD: "team"
            MYSQL_DATABASE: "team_test"
        networks:
            - code-network

    php:
        build: docker/php
        networks:
            - code-network
        dns:
            - ${DNS1}
        volumes:
            - ${BASE_PATH}:/src/www/team-api.local:rw,cached
            - ${BASE_PATH}docker/php/php.ini:/usr/local/etc/php/php.ini:ro
            - ${BASE_PATH}docker/php/docker.ini:/usr/local/etc/php/conf.d/docker.ini:ro
        extra_hosts:
            - "team-api.local:$NGINX_CONTAINER_IP"
        environment:
            PHP_XDEBUG_ENABLED: 1
            XDEBUG_CONFIG: remote_host=10.20.30.1 # sudo ifconfig lo0 alias 10.20.30.1
            PHP_IDE_CONFIG: "serverName=docker"

    nginx:
        image: nginx:latest
        volumes:
            - ${BASE_PATH}:/src/www/team-api.local:rw,cached
            - ${BASE_PATH}docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ${BASE_PATH}docker/nginx/servers/team-api.local.conf:/etc/nginx/servers/team-api.local.conf:ro
        networks:
            - code-network
        dns:
            - ${DNS1}
        ports:
            - "80:80"
        links:
            - php

networks:
    code-network:
        driver: bridge
